#!/bin/sh

if [ $# -eq 0 ]; then
    echo "Supply version number (such as 1.0.1)"
    exit 1
fi

if [ "$(git status --porcelain | wc --lines)" -ne 0 ]; then
    echo "Error: uncommited changes!"
    exit 1
fi

if [ "$(git rev-parse main)" != "$(git rev-parse origin/main)" ]; then
    echo "Error: main branch not sync with origin/main!"
    exit 1
fi

butler push build-release/itchio/release/app-itchio-release.apk gardenapple/mitch:android --userversion $1
