#!/bin/sh

if [ $# -eq 0 ]; then
    echo "Supply version number (such as 1.0.1)"
    exit
fi

butler push build-release/itchio/release/app-itchio-release.apk gardenapple/mitch:android --userversion $1
